### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by gkovelman** [gkpln3/VPNSniffer#2]
Hi,
I like your tool a lot! Really saved me a lot of trouble!

Can you add support for Windows XP? I want to sniff packets that IE6 sends.

Thanks!

**Comment by gkpln3** [comment]
Look carefully at the readme file.
Windows is partially supported (as it is also not guaranteed to work due to the lack of support for shell scripts).

**Comment by gkovelman** [comment]
Hi!
Thanks for the quick response!

But I fail to understand on how to run it on Windows XP, because of the following line:
![image](https://user-images.githubusercontent.com/31855286/81274621-3726cc00-9059-11ea-8fca-b4495f0bd1d4.png)
and the following instruction:
![image](https://user-images.githubusercontent.com/31855286/81274762-6b01f180-9059-11ea-8651-cba6298d5790.png)

Can I install Mac on my Windows XP?

I appreciate the help!

**Comment by Gilnaa** [comment]
Hey Greg,

You can found instructions on downloadmoremac.com
